#finding the symmetrical 95% confidence interval for the mean with unknown variance
# 1. Create a sample dataset
# Replace this example data with your own actual data vector
sample_data <- c(10, 12, 15, 11, 9, 14, 16, 13, 12, 10)

# 2. Run the t.test() function
# The default conf.level is 0.95, so you don't strictly need to specify it.
result <- t.test(sample_data, conf.level = 0.95)

# 3. View the full results
print(result)

# 4. Extract just the confidence interval
print(result$conf.int)


# using the random sample generated from a normal distribution
# Set the random seed for reproducibility
set.seed(47) 

# Generate 30 random data points from a Normal distribution
# mean = 50, sd = 10
sample_data_normal <- rnorm(n = 30, mean = 50, sd = 10)

# View the generated data
print(sample_data_normal)

result <- t.test(sample_data_normal, conf.level = 0.95)
print(result)



#using the random sample generated by setting random seed
# Set a different seed
set.seed(47)

# Generate 20 random integers between 1 and 100
sample_data_integers <- sample(x = 1:100, size = 30, replace = TRUE)

# View the generated data
print(sample_data_integers)

result <- t.test(sample_data_integers, conf.level = 0.95)
print(result)



# genrating a random sample with replacement and finding the symmetrical 
#95% confidence interval for the mean with unknown variance
sample.data <- c(0.61,6.47,2.56,5.44,2.72,0.87,2.77, 6.0, 0.14, 0.75)
sample(sample.data, replace = TRUE)
result <- t.test(sample.data, conf.level = 0.95)
print(result)


# confidence interval for small samples from a non-normal distribution using bootstrap method, see page 352
#non-parametric 95% confidence interval for the mean 
quantile(replicate(1000, mean(sample(sample.data, replace= TRUE))), probs=c(0.025,0.975))



# no built in function for calculating confidence intervals for the variance in r
# so we use the Chi-squared distribution
# 1. Sample Data (replace with your own data)
set.seed(42)
sample_data <- rnorm(n = 30, mean = 50, sd = 10)

# 2. Define Confidence Level
conf_level <- 0.95
alpha <- 1 - conf_level

# 3. Calculate necessary sample statistics
n <- length(sample_data)
sample_var <- var(sample_data)
degrees_freedom <- n - 1

# 4. Find the critical Chi-squared values
# The interval for variance is NOT symmetrical, so we need two different critical values:
# Lower Chi-squared value (for the upper bound of CI formula)
chi_sq_upper <- qchisq(p = alpha / 2, df = degrees_freedom, lower.tail = FALSE)

# Upper Chi-squared value (for the lower bound of CI formula)
chi_sq_lower <- qchisq(p = 1 - (alpha / 2), df = degrees_freedom, lower.tail = FALSE)
# Alternatively: chi_sq_lower <- qchisq(p = alpha / 2, df = degrees_freedom, lower.tail = TRUE)


# 5. Calculate the Confidence Interval for the population variance (sigma^2)
# Formula: [ ((n - 1) * s^2) / B , ((n - 1) * s^2) / A ]
# Where A and B are the respective chi-squared values
lower_bound_var <- (degrees_freedom * sample_var) / chi_sq_upper
upper_bound_var <- (degrees_freedom * sample_var) / chi_sq_lower

# 6. Print the results
cat("Sample Variance (s^2):", sample_var, "\n")
cat(conf_level * 100, "% Confidence Interval for Variance [σ^2]: [", 
    lower_bound_var, ", ", upper_bound_var, "]\n")

# If you also need the Confidence Interval for the Standard Deviation (σ):
lower_bound_sd <- sqrt(lower_bound_var)
upper_bound_sd <- sqrt(upper_bound_var)
cat(conf_level * 100, "% Confidence Interval for Std Dev [σ]: [", 
    lower_bound_sd, ", ", upper_bound_sd, "]\n")



#95% confidence interval for the proportion is
binom.test(x,n,conf.level = 0.95)
binom.test(1,20,conf.level = 0.95)


# 95% confidence interval for the proportion is
poisson.test(x,n,conf.level = 0.95)
poisson.test(1,20,conf.level = 0.90)

#both are giving the same result
poisson.test(1,1,conf.level = 0.90) #x=1, n=1
poisson.test(1,conf.level = 0.90)  #x=1




# confidence interval for two sample normal means, pg 364
# 1. Define Sample Data and Population Variances
# Replace these with your actual data and known variances
sample1_data <- c(10, 12, 15, 11, 9, 14, 16, 13, 12, 10)
sample2_data <- c(20, 22, 25, 21, 19, 24, 26, 23, 22, 20)

pop_var1 <- 4.0   # Known population variance for sample 1
pop_var2 <- 5.0   # Known population variance for sample 2

# 2. Calculate necessary sample statistics
n1 <- length(sample1_data)
n2 <- length(sample2_data)
mean1 <- mean(sample1_data)
mean2 <- mean(sample2_data)
diff_means <- mean1 - mean2

# 3. Define the confidence level and find the critical Z-value
conf_level <- 0.95
alpha <- 1 - conf_level
# qnorm(1 - alpha/2) gives the Z-value for the specified confidence level (e.g., 1.96)
z_critical <- qnorm(1 - alpha/2) 

# 4. Calculate the standard error of the difference in means
std_error_diff <- sqrt(pop_var1 / n1 + pop_var2 / n2)

# 5. Calculate the Margin of Error (ME)
margin_of_error <- z_critical * std_error_diff

# 6. Calculate the Confidence Interval bounds
lower_bound <- diff_means - margin_of_error
upper_bound <- diff_means + margin_of_error

# 7. Print the results
cat("Difference in Sample Means (x1 - x2):", diff_means, "\n")
cat("standard error difference:", std_error_diff,"\n")
cat("Margin of Error:", margin_of_error, "\n")
cat(conf_level * 100, "% Confidence Interval for (mu1 - mu2): [", 
    lower_bound, ", ", upper_bound, "]\n")



#r code for the difference between means with unknown but equal variances - pg 365
# 1. Define two sample datasets
# Replace this sample data with your actual data vectors
sample1 <- c(10.2, 12.5, 11.8, 9.7, 13.1, 10.5, 12.0)
sample2 <- c(15.1, 14.8, 16.2, 14.5, 15.9, 13.9)

# 2. Perform the two-sample t-test with equal variances assumption
# The 'var.equal = TRUE' argument is critical here.
# The default confidence level is 0.95.
result <- t.test(sample1, sample2, var.equal = TRUE, conf.level = 0.95)

# 3. Print the full results
print(result)

# 4. Extract just the confidence interval for the difference in means
print(result$conf.int)


#r code for the difference betwen means with unknown but non-equal variances pg-366
# 1. Define two sample datasets with potentially different variances
# Note the difference in the spread of numbers in sample 2 vs sample 1
sample1 <- c(10.2, 12.5, 11.8, 9.7, 13.1, 10.5, 12.0)
sample2 <- c(15.1, 18.8, 12.2, 11.5, 19.9, 17.9)

# 2. Perform the two-sample t-test with unequal variances assumption
# R defaults to Welch's method (var.equal = FALSE)
result <- t.test(sample1, sample2, conf.level = 0.95)

# 3. Print the full results
print(result)

# 4. Extract just the confidence interval for the difference in means
print(result$conf.int)



# f test and its relevancy for t test for equality or inequality of variances, page 368
# Sample Data
sample1 <- c(10.2, 12.5, 11.8, 9.7, 13.1, 10.5, 12.0)
sample2 <- c(15.1, 18.8, 12.2, 11.5, 19.9, 17.9)

# 1. Perform the F-test for equality of variances
variance_test_result <- var.test(sample1, sample2)

print(variance_test_result)
p_value_f_test <- variance_test_result$p.value

# 2. Use an if-else condition to choose the appropriate t-test
if (p_value_f_test >= 0.05) {
  cat("P-value for F-test (", round(p_value_f_test, 3), ") is large. Using POOLED t-test.\n")
  t_test_result <- t.test(sample1, sample2, var.equal = TRUE)
} else {
  cat("P-value for F-test (", round(p_value_f_test, 3), ") is small. Using WELCH'S t-test.\n")
  # Welch's is R's default, so var.equal=FALSE is implicit
  t_test_result <- t.test(sample1, sample2) 
}

# 3. Print the results of the chosen t-test
print(t_test_result)




# two population proportions test binomial
# Define the counts of successes and total trials as vectors
successes <- c(25,20)
trials <- c(100, 150)

# Perform the proportion test
# The 'correct = TRUE' argument (default) applies a continuity correction
result <- prop.test(x = successes, n = trials, conf.level = 0.95, correct = FALSE)

# Print the results
print(result)




# ratio of two poisson parameters
# Define the counts of successes and total trials as vectors
counts <- c(150,650)
exposure_times <- c(500, 4500)

# Perform the proportion test
# The 'correct = TRUE' argument (default) applies a continuity correction
result <- poisson.test(x = counts, T = exposure_times, conf.level = 0.99)
# Print the results
print(result)


# difference between two poisson parameters
# Define counts of events and their corresponding time/exposure units
counts1 <- 150
exposure1 <- 500  # e.g., 10 days, 10 person-years
counts2 <- 650
exposure2 <- 4500  # e.g., 15 days, 15 person-years

# Calculate sample rates
rate1_hat <- counts1 / exposure1
rate2_hat <- counts2 / exposure2

# Calculate the difference in rates
diff_rates <- rate1_hat - rate2_hat

# Define the confidence level and Z-value (1.96 for 95% CI)
conf_level <- 0.95
z_critical <- qnorm(1 - (1 - conf_level) / 2) 
print(z_critical)
# Calculate the Standard Error of the difference
# Since mean = variance in Poisson, the variance estimate is the rate itself
SE_diff <- sqrt(rate1_hat / exposure1 + rate2_hat / exposure2)

# Calculate Margin of Error
margin_of_error <- z_critical * SE_diff

# Calculate the Confidence Interval bounds
lower_bound <- diff_rates - margin_of_error
upper_bound <- diff_rates + margin_of_error

cat("Difference in Rates (lambda1 - lambda2):", diff_rates, "\n")
cat("Margin of Error:", margin_of_error, "\n")
cat(conf_level * 100, "% Confidence Interval for Difference: [", 
    lower_bound, ", ", upper_bound, "]\n")





# confidence interval for paired data
# Sample data: Weights before and after a treatment for 10 subjects
before <- c(65, 70, 68, 75, 72, 69, 71, 70, 66, 74)
after <- c(68, 72, 70, 74, 75, 71, 70, 73, 69, 75)

# Calculate the 95% confidence interval using t.test()
# The 'paired = TRUE' argument is essential
result <- t.test(after, before, paired = TRUE, conf.level = 0.95)

# Print the full results
print(result)

# To get just the confidence interval:
print(result$conf.int)

